# 20231030 Javascript/Callback and Promises

## Modern JavaScript from the Beginning - Second Edition

### Callback and Promises

Bu örnek iyi. Promise meselesini açıklıyor.

/Users/bulent/git-repos/oreilly-courses/javascript/mjfb-brad-traversy/09-asynchronous-javascript/11-promise-all

###  Fetch API and Async Wait

- the Fetch API is a more modern way to communicate with servers and make HTTP requests. And we already talked about what a GET request is, POST, PUT, DELETE requests.
- Async Await is a newer syntax for working with not only the Fetch API, but any promises. And it's an alternative syntax to the, to .then which is what we've been working with up to this point. I go as far as to say that Async Await is more common now than using the .then syntax.

```javascript
async function getAllData() {
  const movies = await getData('./movies.json');
  const actors = await getData('./actors.json');
  const directors = await getData('./directors.json');
  console.log(movies, actors, directors);
  console.log('1234');
}

console.log('123')
```

'123' önce basılır, await fonksiyon içinde bekletme yapmaz.

#### Multiple promises, Async/Await Sample

```javascript
function getData(endpoint) {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.open('GET', endpoint);

    xhr.onreadystatechange = function () {
      if (this.readyState === 4) {
        if (this.status === 200) {
          resolve(JSON.parse(this.responseText));
        } else {
          reject('Error: Something went wrong');
        }
      }
    };

    setTimeout(() => {
      xhr.send();
    }, Math.floor(Math.random() * 3000) + 1000);
  });
}

// getData('./movies.json')
//   .then((movies) => {
//     console.log(movies);
//     return getData('./actors.json');
//   })
//   .then((actors) => {
//     console.log(actors);
//     return getData('./directors.json');
//   })
//   .then((directors) => {
//     console.log(directors);
//   })
//   .catch((error) => console.log(error));

async function getAllData() {
  const movies = await getData('./movies.json');
  const actors = await getData('./actors.json');
  const directors = await getData('./directors.json');
  console.log(movies, actors, directors);
}

async function getAllDataWithFetch() {
  const moviesRes = await fetch('./movies.json');
  const movies = await moviesRes.json();

  const actorsRes = await fetch('./actors.json');
  const actors = await actorsRes.json();

  const directorsRes = await fetch('./directors.json');
  const directors = await directorsRes.json();

  console.log(movies, actors, directors);
}

async function getAllDataPromiseAll() {
  const [moviesRes, actorsRes, directorsRes] = await Promise.all([
    fetch('./movies.json'),
    fetch('./actors.json'),
    fetch('./directors.json'),
  ]);

  const movies = await moviesRes.json();
  const actors = await actorsRes.json();
  const directors = await directorsRes.json();

  console.log(movies, actors, directors);
}

async function getAllDataPromiseAll2() {
  const [movies, actors, directors] = await Promise.all([
    fetch('./movies.json').then((res) => res.json()),
    fetch('./actors.json').then((res) => res.json()),
    fetch('./directors.json').then((res) => res.json()),
  ]);

  console.log(movies, actors, directors);
}

// getAllData();
// getAllDataWithFetch();
// getAllDataPromiseAll();
getAllDataPromiseAll2();

```

###  Running fetch inside NODE REPL

```shell
// Now you can use the fetch function
// Fetching from an API
fetch('https://api.github.com/users/bradtraversy')
  .then((response) => response.json())
  .then((data) => {
    console.log(data);
  });

```

### Popular Sites

[Random User Generator](https://randomuser.me/)
[Free Fake API for testing and prottyping](https://jsonplaceholder.typicode.com/)
[This is a super simple service for generating different HTTP codes.](https://httpstat.us/)

###  Error handling

Fetch API doesn't trigger catch in any response code case. Only on network errors.  AXIOS behaves differently.
